/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lonly_example_ndkdemo2_MyNDK */

#ifndef _Included_com_lonly_example_ndkdemo2_MyNDK
#define _Included_com_lonly_example_ndkdemo2_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lonly_example_ndkdemo2_MyNDK
 * Method:    sequare
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_lonly_example_ndkdemo2_MyNDK_sequare
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
